urls.py
from django.urls import path

from . import views

app_name = 'otbank'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<str:pk>/', views.ConstraintView.as_view(), name='constraint'),
]

models.py
from django.db import models


"""
class Subfield(models.Model):
    subfield_name = models.CharField(max_length=200, primary_key=True)

    def __str__(self):
        return self.subfield_name
"""


class Constraint(models.Model):
    name = models.CharField(max_length=200, primary_key=True)

    def __str__(self):
        return self.name


class Definition(models.Model):
    constraint = models.ForeignKey(Constraint, on_delete=models.CASCADE)
    definition_text = models.CharField(max_length=1000)
    definition_citation = models.CharField(max_length=1000)
    ''' first definition should be explicitly called as true '''
    primary = models.BooleanField(default=False)

    def __str__(self):
        return self.definition_text


class Tableau(models.Model):
    tab_constraints = models.ManyToManyField(Constraint)
    code = models.CharField(max_length=1000)
    tab_citation = models.CharField(max_length=1000)

    def __str__(self):
        return self.code

views.py
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views import generic

from .models import Constraint, Definition, Tableau


class IndexView(generic.ListView):
    model = Constraint
    template_name = 'otbank/index.html'
    context_object_name = 'constraint_list'


class ConstraintView(generic.DetailView):
    model = Constraint
    template_name = 'otbank/constraint.html'

templates/otbank/constraint.html
{% load static %}

<title>OTbank | {{ constraint.name }}</title>
<link rel="stylesheet" type="text/css" href="{% static 'otbank/style.css' %}">
<link rel="shortcut icon" type="image/png" href="{% static 'otbank/images/favicon.ico' %}"/>

<div class="body">
<h1 class="content">{{ constraint.name }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

{% if constraint.definition_set.all|length > 0 %}
    <ol type="1" class="content">
    {% for def in constraint.definition_set.all %}
        <li><p class="citation">{{ def.definition_text }}<span class="citationtext">{{ def.definition_citation }}</span></p></li>
    {% endfor %}
    </ol>
{% else %}
    <p>No definitions listed for {{ constraint.name }}.</p>
{% endif %}
</div>

templates/otbank/index.html
{% load static %}

<title>OTbank | Home</title>
<link rel="stylesheet" type="text/css" href="{% static 'otbank/style.css' %}">
<link rel="shortcut icon" type="image/png" href="{% static 'otbank/images/favicon.ico' %}"/>

<div class="body">
<h1 class="content" align="center">OT Constraint Databank</h1>

{% if constraint_list %}
    <ul class="content" align="left">
    {% for constraint in constraint_list %}
        <li align="left"><a href="{% url 'otbank:constraint' constraint.pk %}">{{ constraint.name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No subfields are available.</p>
{% endif %}

</div>

templates/otbank/subfield.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'otbank/style.css' %}">

<h1>{{ subfield.subfield_name }}</h1>

{% if these_constraints %}
    <ul>
    {% for constraint in these_constraints %}
        <li><a href="{% url 'otbank:constraint' "Phonology" constraint.pk %}">{{ constraint.constraint_name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No constraints are available.</p>
{% endif %}